### ISSUE TITLE
Git 提交指南中 特性缩写 feat 更改为 feature 会否更清晰？

### ISSUE THREAD

**Issue by EthanLin-TWer** [udacity/frontend-nanodegree-styleguide-zh#4]
Hi Udacity team,

[Git 提交信息样式指南](https://github.com/udacity/frontend-nanodegree-styleguide-zh/blob/master/%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%B8%88%E7%BA%B3%E7%B1%B3%E5%AD%A6%E4%BD%8D%E6%A0%B7%E5%BC%8F%E6%8C%87%E5%8D%97%20-%20Git.md) README （原文见下）中，注意到新功能用的前缀是 `feat`，猜想是 `feature` 的缩写。使用 "feat abbreviation" 搜索了一下，发现 feat 确是 `featuring` 的缩写，不过 `featuring` 此时是 [用作动词](https://www.google.com.hk/search?q=%22featuring%22+definition)，与 feature 特性的意思还有差别。

因此想问用 `feat` 做缩写是否有其他的原因（比如整个平台都已采用这样的规范）？直接用 `feature` 会不会更清晰？从长度方面考虑似乎也不是问题，因为 `refactor` 比 `feature` 也还要长些。

> ```
> ## 类型
> 
> 类型位于在标题内，有以下几种可能： 
> 
> * feat： 新功能
> * fix：错误修复
> * docs：文档修改 
> * style：格式、分号缺失等，代码无变动
> * refactor：生产代码重构
> ...
> ```

**Comment by weierz** [comment]
Hi linesh,

[Git Guide](https://udacity.github.io/git-styleguide/) 这样会不会更清晰一些呢？

![git_the_type](https://cloud.githubusercontent.com/assets/14329786/23688829/a7afa656-03f1-11e7-8ebd-f8b82959e859.png)

**Comment by EthanLin-TWer** [comment]
我想的是这样：

![image](https://cloud.githubusercontent.com/assets/11895199/23689345/e693b512-03f4-11e7-90a6-07ed591b636f.png)

文档上看确实很直观。不过我猜更多时候我们是直接看 `git log` 或者在 Github 上面看到提交记录，此时看到这个 `feat` 阅读者可能还要反应一下才知道是 `feature` 的意思，既然如此，直接在提交时写全称 `feature` 就会清晰一些，避免了可能因为这种思维中断而带来阅读上的不连贯。比如：

```git log
* 4caa5ed fix: No idea one service is failing
* 2dfaa8a feature: Exclude other absent days from totalDays calculation
* a740005 chore: Intellij changes
* 3443663 feature: Add 'Commuting' to weekdayProjects
* a3b01e8 style: Put effective days column in the last as it's the most not important
* 4faabbc fix: Fix template markdown generation error
* 39cf983 chore: Intellij changes
* 611e0c2 chore: Add settings.json to VCS, fixing broken pipeline
* a048a69 fix: Fix clients/projects can be undefined/null issues
* a8bba77 chore: Intellij changes
```
